### ISSUE TITLE
Unable to add classes to files post update

### ISSUE THREAD

**Issue by AlisAquilae** [mdelobelle/metadatamenu#594]
Hi there,

I just updated to metadata menu V0.8.1 and am experiencing some issues

I am currently unable to add any of my existing classes to new files. I can choose a fileclass upon creation, which shows all my existing classes, but when I select one it does not do anything and leaves me with an empty note without a class. Moreover, when I right click the note and go to field options, the menu does not pop up at all. 

All of my classes are still present. The icons besides the files still show properly, the fieldclass settings are still fine, and all settings are the same. I checked and re-added all file paths (i.e. base class and fileClass folder), but that did not help either. 

I should note that I updated because I was experiencing another issue where 1 specific note was not shown in queries for inlinks. I don't know if and how that could have anything to do with it, but in the case it does I wanted to have mentioned it anyways.

I have very little knowledge of programming or bug-fixing, but if there is anything I can do, any information I can provide, do let me know

**Comment by mdelobelle** [comment]
Hi. Are there any error printed in the console when choosing a fileclass for new file? 
and when you right click > fields options?

**Comment by AlisAquilae** [comment]
Yes, quite a few of them. This is the console log after opening obsidian, 
![image](https://github.com/mdelobelle/metadatamenu/assets/80721939/b91974af-011f-4c4e-9e3b-5bc447410de4)
This is the log after creating a new note
![image](https://github.com/mdelobelle/metadatamenu/assets/80721939/92b32435-33a1-4405-b428-8e87edcbae2a)
And after clicking field options
![image](https://github.com/mdelobelle/metadatamenu/assets/80721939/e58f551a-6687-40d9-8ccf-1386aeb86f52)

**Comment by mdelobelle** [comment]
ok could you type "MetadataMenu.fieldIndex" in the console and paste the result here? (please click on the little arrow on the left to expand the object before taking the screenshot)

**Comment by AlisAquilae** [comment]
Done
![image](https://github.com/mdelobelle/metadatamenu/assets/80721939/19d81585-6f72-4d96-a44e-022eb4c5f60e)

**Comment by mdelobelle** [comment]
The globalFileClass seems to cause the issue (see the list of 4 undefined values).
Could you paste the content of your gloabl fileclass (the source frontmatter of the .md file) please?

**Comment by AlisAquilae** [comment]
---
fields:
  - name: Parents
    type: MultiFile
    options:
      dvQueryString: current.file.inlinks
    path: ""
    id: xZsc2u
  - name: title
    type: Input
    options: {}
    path: ""
    id: m2teu0
  - name: Draft
    type: Boolean
    options: {}
    path: ""
    id: QBQtQz
  - name: Status
    type: Select
    options:
      valuesList:
        "1": Not Started
        "2": In Progress
        "3": Done
        "4": To Revisit
      sourceType: ValuesList
      valuesListNotePath: ""
      valuesFromDVQuery: ""
    path: ""
    id: rL6xOa
version: "2.49"
limit: 20
mapWithTag: false
icon: shield-x
tagNames: 
filesPaths: 
bookmarksGroups: 
excludes: 
extends: 
savedViews: []
favoriteView: 
fieldsOrder:
  - m2teu0
  - xZsc2u
  - QBQtQz
  - rL6xOa
---

**Comment by mdelobelle** [comment]
ok thanks i can reproduce and I've located the issue. Will try to fix it asap

**Comment by AlisAquilae** [comment]
Great! Thank you so much for taking the time to look at my issue. Loving the plugin and looking forward to being able to continue working with it <3

**Comment by mdelobelle** [comment]
Thanks a lot, very much appreciated :) 
could you test this version https://github.com/mdelobelle/metadatamenu/releases/tag/0.8.2-beta-1 ?
replace the `main.js` in the `.obsidian/plugins/metadata-menu` folder of your vault
Then disable/enable the plugin 

The issue should be solved for global fileclass, we'll see if there are new issues coming up

**Comment by AlisAquilae** [comment]
Just tried it. The issue seems to be resolved, and everything seems to be working the way it should (though I still have another issue which I'd hoped would disappear alongside it, but I think that is dataview related and not metadata menu). 

One thing is that I had the console open alongside trying all the usual buttons and actions. On one occasion the global fileclass did not load, only the class I added myself. The console also gave a warning about this:

![image](https://github.com/mdelobelle/metadatamenu/assets/80721939/b81532b7-aeba-4bf8-bc08-f9a6fac10019)

I tried repating the steps I had until then but have not been able to reproduce this or narrow it down. Don't know whether it was a slight hiccup or whether there is still a little issue somewhere, but wanted to have shared it anyways

**Comment by mdelobelle** [comment]
Great! I will release this version then. 
This warning isn't related to metadata menu and I have to say that I have no idea where this comes from....

I'll close this issue, don't hesitate to open a new one should you encounter a new problem
